export const consts = {
    STANDARD_OPERATION: 0,
    ADD_OPERATION: 1,
    EDITING_OPERATION: 2,
    VIEW_USER_LOG_OPERATION: 3,

    MAX_LENGTH_LAST_NAME: 40,
    MAX_LENGTH_FIRST_NAME: 40,
    MAX_LENGTH_MIDDLE_NAME: 50
};